In [1]:
import json
import os
from tqdm import tqdm
from collections import defaultdict
import numpy as np
from typing import *
import time
import copy
import warnings

from data.openai import *
from data.generation import *
from data.finetune import *
from data.inference import *
from data.io import *
from data.evaluation import *
from data.split import *

from utils import cleanse_answer
from utils.paths import *
from utils.metadata import *

In [2]:
import openai
openai.api_key = "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"

In [3]:
ALL_DATASETS = [
    "single_eq", "addsub", "multiarith", "gsm8k", "aqua", "svamp",
    "date_understanding", "coin_flip",
    "tracking_shuffled_objects", "last_letter_concatenation",
    "commonsense_qa", "strategy_qa",
]
datasets = ALL_DATASETS

# Compile Summary

In [142]:
summary = []

with warnings.catch_warnings():
    warnings.simplefilter(action='ignore', category=RuntimeWarning)
    
    # Compile teacher model performance
    template = None
    completion_key = "zs_cot"
    file_key = "zs_cot"
    method = "zs_cot"
    base_model_key = "text-davinci-002"
    
    model_key = "{}".format(base_model_key)
    for dataset_key in datasets:
        completion_data = load_completion_data(completion_key, dataset_key, model_key)
        item = dict()
        item["dataset"] = dataset_key
        item["method"] = method
        item["base_model"] = "idavinci"
        item["shot"] = ""
        item["aug"] = ""
        evaluation = evaluate_completions(completion_data, dataset_key, template=template, print_metrics=False)
        item.update(get_evaluation_metrics(evaluation))
        summary.append(item)
    
    # Compile student model performance
    template = None
    for base_model_key in ["ada", "babbage", "curie"]:
        for dataset_key in datasets:
            completion_keys = [
                "ft",
                "zs_cot",
                "finetune_cot",
                "finetune_cot",
                "finetune_cot",
                "finetune_cot",
            ]
            file_keys = [
                "{}_train".format(dataset_key),
                "",
                "zs_cot_special_{}_train".format(dataset_key),
                "zs_cot_special_{}_8shot".format(dataset_key),
                "zs_cot_special_{}_32shot".format(dataset_key),
                "zs_cot_special_{}_128shot".format(dataset_key),
            ]
            methods = [
                "ft",
                "zs_cot",
                "ft_cot",
                "ft_cot",
                "ft_cot",
                "ft_cot",
            ]
            shots = [
                "", "", "", 8, 32, 128
            ]
            augs = [
                "", "", 1, 1, 1, 1
            ]
            for shot in ["", 8, 32, 128]:
                if shot == "":
                    shot_str = ""
                else:
                    shot_str = "{}shot_".format(shot)
                for aug in [2, 4, 8, 16, 32]:
                    completion_keys.append("finetune_cot")
                    file_keys.append("zs_cot_special_{}_{}{}aug".format(dataset_key, shot_str, aug))
                    methods.append("ft_cot")
                    shots.append(shot)
                    augs.append(aug)
                    
            for completion_key, file_key, method, shot, aug in zip(
                completion_keys, file_keys, methods, shots, augs):
                if method == "zs_cot":
                    model_key = base_model_key
                else:
                    model_key = "{}_{}".format(base_model_key, file_key)
                completion_data = load_completion_data(completion_key, dataset_key, model_key)
                if not completion_data:
                    continue
                item = dict()
                item["dataset"] = dataset_key
                item["method"] = method
                item["base_model"] = base_model_key
                item["shot"] = shot
                item["aug"] = aug
                if completion_data:
                    if "special" in file_key:
                        template = "special"
                    else:
                        template = None
                    evaluation = evaluate_completions(completion_data, dataset_key, template=template, print_metrics=False)
                item.update(get_evaluation_metrics(evaluation))
                summary.append(item)

In [143]:
summary = pd.DataFrame(summary)
summary.sort_values(["dataset", "method", "base_model"])[::4]

,dataset,method,base_model,shot,aug,accuracy,contains_prediction,contains_answer,reason_complete,accuracy_when_reason_complete,accuracy_when_reason_incomplete,complete,accuracy_when_complete,accuracy_when_incomplete,contains_prefix,accuracy_with_prefix,accuracy_without_prefix
18,addsub,ft,ada,,,0.084034,1.000000,0.084034,NaN,NaN,NaN,0.991597,0.084746,0.000000,NaN,NaN,NaN
21,addsub,ft_cot,ada,8,1,0.008403,0.857143,0.243697,NaN,NaN,NaN,0.000000,NaN,0.008403,0.000000,NaN,0.008403
112,addsub,ft_cot,babbage,8,1,0.033613,0.915966,0.033613,NaN,NaN,NaN,0.966387,0.034783,0.000000,0.882353,0.028571,0.071429
204,addsub,ft_cot,curie,8,1,0.126050,0.798319,0.134454,NaN,NaN,NaN,0.747899,0.146067,0.066667,0.899160,0.140187,0.000000
110,addsub,zs_cot,babbage,,,0.000000,0.899160,0.067227,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
147,aqua,ft,babbage,,,0.212598,0.889764,0.000000,NaN,NaN,NaN,0.889764,0.238938,0.000000,NaN,NaN,NaN
60,aqua,ft_cot,ada,128,1,0.177165,0.637795,0.000000,NaN,NaN,NaN,0.531496,0.259259,0.084034,0.523622,0.248120,0.099174
152,aqua,ft_cot,babbage,128,1,0.149606,0.759843,0.000000,NaN,NaN,NaN,0.712598,0.198895,0.027397,0.728346,0.194595,0.028986
244,aqua,ft_cot,curie,128,1,0.125984,0.712598,0.000000,NaN,NaN,NaN,0.618110,0.159236,0.072165,0.625984,0.157233,0.073684
4,aqua,zs_cot,idavinci,,,0.296300,0.879000,0.000000,0.440400,0.394187,0.219264,NaN,NaN,NaN,NaN,NaN,NaN
75,coin_flip,ft_cot,ada,,1,0.993333,1.000000,0.000000,NaN,NaN,NaN,0.000000,NaN,0.993333,1.000000,0.993333,NaN
167,coin_flip,ft_cot,babbage,,1,1.000000,1.000000,0.000000,NaN,NaN,NaN,0.000000,NaN,1.000000,1.000000,1.000000,NaN
259,coin_flip,ft_cot,curie,,1,0.980000,1.000000,0.000000,NaN,NaN,NaN,0.000000,NaN,0.980000,1.000000,0.980000,NaN
74,coin_flip,zs_cot,ada,,,0.046667,0.193333,0.000000,0.000000,NaN,0.046667,NaN,NaN,NaN,NaN,NaN,NaN
91,commonsense_qa,ft,ada,,,0.516790,1.000000,0.000000,NaN,NaN,NaN,1.000000,0.516790,NaN,NaN,NaN,NaN
94,commonsense_qa,ft_cot,ada,8,1,0.152334,0.819001,0.000000,NaN,NaN,NaN,0.001638,0.500000,0.151764,0.549550,0.150522,0.154545
186,commonsense_qa,ft_cot,babbage,8,1,0.127764,0.582310,0.000000,NaN,NaN,NaN,0.257166,0.130573,0.126792,0.545455,0.099099,0.162162
278,commonsense_qa,ft_cot,curie,8,1,0.138411,0.668305,0.000000,NaN,NaN,NaN,0.131040,0.193750,0.130066,0.281736,0.005814,0.190422
184,commonsense_qa,zs_cot,babbage,,,0.202293,0.998362,0.000000,0.000000,NaN,0.202293,NaN,NaN,NaN,NaN,NaN,NaN
159,date_understanding,ft,babbage,,,0.315315,1.000000,0.000000,NaN,NaN,NaN,1.000000,0.315315,NaN,NaN,NaN,NaN
71,date_understanding,ft_cot,ada,32,1,0.153153,1.000000,0.000000,NaN,NaN,NaN,0.981982,0.155963,0.000000,0.981982,0.155963,0.000000
163,date_understanding,ft_cot,babbage,32,1,0.189189,0.990991,0.000000,NaN,NaN,NaN,0.972973,0.194444,0.000000,0.972973,0.194444,0.000000
255,date_understanding,ft_cot,curie,32,1,0.180180,0.945946,0.000000,NaN,NaN,NaN,0.936937,0.182692,0.142857,0.927928,0.184466,0.125000
252,date_understanding,zs_cot,curie,,,0.153153,1.000000,0.000000,0.000000,NaN,0.153153,NaN,NaN,NaN,NaN,NaN,NaN
233,gsm8k,ft,curie,,,0.061410,0.994693,0.000000,NaN,NaN,NaN,0.998484,0.061503,0.000000,NaN,NaN,NaN
55,gsm8k,ft_cot,ada,128,1,0.016679,0.961334,0.000000,NaN,NaN,NaN,0.753601,0.019115,0.009231,0.763457,0.018868,0.009615
146,gsm8k,ft_cot,babbage,128,1,0.016679,0.977255,0.000000,NaN,NaN,NaN,0.648218,0.018713,0.012931,0.652009,0.017442,0.015251
238,gsm8k,ft_cot,curie,128,1,0.026535,0.984079,0.000000,NaN,NaN,NaN,0.774071,0.030362,0.013423,0.754359,0.031156,0.012346
3,gsm8k,zs_cot,idavinci,,,0.420723,0.989081,0.000000,0.696542,0.527760,0.175037,NaN,NaN,NaN,NaN,NaN,NaN
87,last_letter_concatenation,ft_cot,ada,,1,0.506667,1.000000,0.000000,NaN,NaN,NaN,0.006667,1.000000,0.503356,1.000000,0.506667,NaN
179,last_letter_concatenation,ft_cot,babbage,,1,0.506667,1.000000,0.000000,NaN,NaN,NaN,0.000000,NaN,0.506667,1.000000,0.506667,NaN
271,last_letter_concatenation,ft_cot,curie,,1,0.520000,1.000000,0.000000,NaN,NaN,NaN,0.000000,NaN,0.520000,1.000000,0.520000,NaN
86,last_letter_concatenation,zs_cot,ada,,,0.000000,1.000000,0.000000,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
24,multiarith,ft,ada,,,0.088889,1.000000,0.000000,NaN,NaN,NaN,1.000000,0.088889,NaN,NaN,NaN,NaN
27,multiarith,ft_cot,ada,8,1,0.044444,0.983333,0.000000,NaN,NaN,NaN,0.000000,NaN,0.044444,0.000000,NaN,0.044444
31,multiarith,ft_cot,ada,,4,0.077778,0.994444,0.000000,NaN,NaN,NaN,0.961111,0.080925,0.000000,0.961111,0.080925,0.000000
35,multiarith,ft_cot,ada,8,2,0.033333,0.883333,0.000000,NaN,NaN,NaN,0.627778,0.044248,0.014925,0.600000,0.027778,0.041667
39,multiarith,ft_cot,ada,8,32,0.027778,0.994444,0.000000,NaN,NaN,NaN,0.972222,0.028571,0.000000,0.977778,0.028409,0.000000
43,multiarith,ft_cot,ada,32,16,0.033333,0.994444,0.000000,NaN,NaN,NaN,0.933333,0.035714,0.000000,0.938889,0.035503,0.000000
47,multiarith,ft_cot,ada,128,8,0.066667,0.994444,0.000000,NaN,NaN,NaN,0.988889,0.067416,0.000000,0.994444,0.067039,0.000000
118,multiarith,ft_cot,babbage,8,1,0.033333,0.777778,0.000000,NaN,NaN,NaN,0.288889,0.038462,0.031250,0.466667,0.011905,0.052083
122,multiarith,ft_cot,babbage,,4,0.133333,1.000000,0.000000,NaN,NaN,NaN,0.988889,0.134831,0.000000,0.988889,0.134831,0.000000
126,multiarith,ft_cot,babbage,8,2,0.050000,1.000000,0.000000,NaN,NaN,NaN,0.711111,0.054688,0.038462,0.788889,0.049296,0.052632
130,multiarith,ft_cot,babbage,8,32,0.016667,0.977778,0.000000,NaN,NaN,NaN,0.933333,0.011905,0.083333,0.955556,0.011628,0.125000
134,multiarith,ft_cot,babbage,32,16,0.088889,1.000000,0.000000,NaN,NaN,NaN,0.972222,0.085714,0.200000,0.983333,0.084746,0.333333
138,multiarith,ft_cot,babbage,128,8,0.094444,1.000000,0.000000,NaN,NaN,NaN,0.977778,0.096591,0.000000,0.977778,0.096591,0.000000
210,multiarith,ft_cot,curie,8,1,0.005556,0.616667,0.000000,NaN,NaN,NaN,0.388889,0.000000,0.009091,0.544444,0.000000,0.012195
214,multiarith,ft_cot,curie,,4,0.338889,1.000000,0.000000,NaN,NaN,NaN,0.950000,0.356725,0.000000,0.950000,0.356725,0.000000
218,multiarith,ft_cot,curie,8,2,0.022222,0.988889,0.000000,NaN,NaN,NaN,0.794444,0.020979,0.027027,0.972222,0.022857,0.000000
222,multiarith,ft_cot,curie,8,32,0.061111,1.000000,0.000000,NaN,NaN,NaN,0.950000,0.064327,0.000000,0.944444,0.064706,0.000000
226,multiarith,ft_cot,curie,32,16,0.172222,1.000000,0.000000,NaN,NaN,NaN,0.977778,0.176136,0.000000,0.977778,0.176136,0.000000
230,multiarith,ft_cot,curie,128,8,0.277778,1.000000,0.000000,NaN,NaN,NaN,0.983333,0.276836,0.333333,0.983333,0.276836,0.333333
116,multiarith,zs_cot,babbage,,,0.033333,0.927778,0.000000,0.000000,NaN,0.033333,NaN,NaN,NaN,NaN,NaN,NaN
103,single_eq,ft,babbage,,,0.118421,1.000000,0.118421,NaN,NaN,NaN,1.000000,0.118421,NaN,NaN,NaN,NaN
16,single_eq,ft_cot,ada,32,1,0.006579,1.000000,0.026316,NaN,NaN,NaN,0.888158,0.007407,0.000000,0.901316,0.007299,0.000000
107,single_eq,ft_cot,babbage,32,1,0.026316,0.993421,0.039474,NaN,NaN,NaN,0.927632,0.028369,0.000000,0.848684,0.031008,0.000000
199,single_eq,ft_cot,curie,32,1,0.085526,1.000000,0.098684,NaN,NaN,NaN,0.881579,0.097015,0.000000,0.901316,0.094891,0.000000
196,single_eq,zs_cot,curie,,,0.013158,0.980263,0.111842,0.000000,NaN,0.013158,NaN,NaN,NaN,NaN,NaN,NaN
281,strategy_qa,ft,curie,,,0.652111,0.998544,0.000000,NaN,NaN,NaN,1.000000,0.652111,NaN,NaN,NaN,NaN
102,strategy_qa,ft_cot,ada,128,1,0.381368,0.800582,0.000000,NaN,NaN,NaN,0.778748,0.474766,0.052632,0.787482,0.465804,0.068493
194,strategy_qa,ft_cot,babbage,128,1,0.394469,0.807860,0.000000,NaN,NaN,NaN,0.768559,0.486742,0.088050,0.780204,0.479478,0.092715
286,strategy_qa,ft_cot,curie,128,1,0.436681,0.823872,0.000000,NaN,NaN,NaN,0.800582,0.527273,0.072993,0.819505,0.513321,0.088710
11,strategy_qa,zs_cot,idavinci,,,0.533999,0.819089,0.000000,0.715533,0.579773,0.418860,NaN,NaN,NaN,NaN,NaN,NaN
63,svamp,ft_cot,ada,,1,0.043333,0.993333,0.046667,NaN,NaN,NaN,0.913333,0.043796,0.038462,0.923333,0.043321,0.043478
155,svamp,ft_cot,babbage,,1,0.073333,0.996667,0.076667,NaN,NaN,NaN,0.903333,0.077491,0.034483,0.906667,0.077206,0.035714
247,svamp,ft_cot,curie,,1,0.123333,0.996667,0.126667,NaN,NaN,NaN,0.936667,0.131673,0.000000,0.946667,0.130282,0.000000
62,svamp,zs_cot,ada,,,0.030000,0.816667,0.153333,0.000000,NaN,0.030000,NaN,NaN,NaN,NaN,NaN,NaN
79,tracking_shuffled_objects,ft,ada,,,0.324444,1.000000,0.000000,NaN,NaN,NaN,1.000000,0.324444,NaN,NaN,NaN,NaN
82,tracking_shuffled_objects,ft_cot,ada,8,1,0.346667,1.000000,0.000000,NaN,NaN,NaN,1.000000,0.346667,NaN,1.000000,0.346667,NaN
174,tracking_shuffled_objects,ft_cot,babbage,8,1,0.271111,0.897778,0.000000,NaN,NaN,NaN,0.986667,0.265766,0.666667,0.995556,0.267857,1.000000
266,tracking_shuffled_objects,ft_cot,curie,8,1,0.284444,1.000000,0.000000,NaN,NaN,NaN,1.000000,0.284444,NaN,1.000000,0.284444,NaN
172,tracking_shuffled_objects,zs_cot,babbage,,,0.382222,1.000000,0.000000,0.000000,NaN,0.382222,NaN,NaN,NaN,NaN,NaN,NaN

In [144]:
pd.set_option('display.max_rows', 100)
summary = pd.DataFrame(summary)
summary = summary.sort_values(["dataset", "method", "base_model", "dataset", "shot", "aug"])
summary[summary.dataset == "multiarith"]

,dataset,method,base_model,shot,aug,accuracy,contains_prediction,contains_answer,reason_complete,accuracy_when_reason_complete,accuracy_when_reason_incomplete,complete,accuracy_when_complete,accuracy_when_incomplete,contains_prefix,accuracy_with_prefix,accuracy_without_prefix
24,multiarith,ft,ada,,,0.088889,1.000000,0.0,NaN,NaN,NaN,1.000000,0.088889,NaN,NaN,NaN,NaN
115,multiarith,ft,babbage,,,0.177778,1.000000,0.0,NaN,NaN,NaN,1.000000,0.177778,NaN,NaN,NaN,NaN
207,multiarith,ft,curie,,,0.150000,0.988889,0.0,NaN,NaN,NaN,0.988889,0.151685,0.000000,NaN,NaN,NaN
27,multiarith,ft_cot,ada,8,1,0.044444,0.983333,0.0,NaN,NaN,NaN,0.000000,NaN,0.044444,0.000000,NaN,0.044444
35,multiarith,ft_cot,ada,8,2,0.033333,0.883333,0.0,NaN,NaN,NaN,0.627778,0.044248,0.014925,0.600000,0.027778,0.041667
36,multiarith,ft_cot,ada,8,4,0.016667,0.994444,0.0,NaN,NaN,NaN,0.972222,0.017143,0.000000,0.950000,0.017544,0.000000
37,multiarith,ft_cot,ada,8,8,0.033333,1.000000,0.0,NaN,NaN,NaN,0.944444,0.035294,0.000000,0.933333,0.035714,0.000000
38,multiarith,ft_cot,ada,8,16,0.022222,1.000000,0.0,NaN,NaN,NaN,0.977778,0.022727,0.000000,0.977778,0.022727,0.000000
39,multiarith,ft_cot,ada,8,32,0.027778,0.994444,0.0,NaN,NaN,NaN,0.972222,0.028571,0.000000,0.977778,0.028409,0.000000
28,multiarith,ft_cot,ada,32,1,0.038889,1.000000,0.0,NaN,NaN,NaN,0.777778,0.028571,0.075000,0.777778,0.028571,0.075000
40,multiarith,ft_cot,ada,32,2,0.038889,1.000000,0.0,NaN,NaN,NaN,0.927778,0.041916,0.000000,0.922222,0.042169,0.000000
41,multiarith,ft_cot,ada,32,4,0.027778,1.000000,0.0,NaN,NaN,NaN,0.966667,0.028736,0.000000,0.966667,0.028736,0.000000
42,multiarith,ft_cot,ada,32,8,0.027778,1.000000,0.0,NaN,NaN,NaN,0.977778,0.028409,0.000000,0.977778,0.028409,0.000000
43,multiarith,ft_cot,ada,32,16,0.033333,0.994444,0.0,NaN,NaN,NaN,0.933333,0.035714,0.000000,0.938889,0.035503,0.000000
44,multiarith,ft_cot,ada,32,32,0.011111,0.994444,0.0,NaN,NaN,NaN,0.900000,0.012346,0.000000,0.905556,0.012270,0.000000
29,multiarith,ft_cot,ada,128,1,0.061111,1.000000,0.0,NaN,NaN,NaN,0.944444,0.064706,0.000000,0.938889,0.065089,0.000000
45,multiarith,ft_cot,ada,128,2,0.033333,1.000000,0.0,NaN,NaN,NaN,0.966667,0.034483,0.000000,0.972222,0.034286,0.000000
46,multiarith,ft_cot,ada,128,4,0.072222,1.000000,0.0,NaN,NaN,NaN,0.961111,0.075145,0.000000,0.966667,0.074713,0.000000
47,multiarith,ft_cot,ada,128,8,0.066667,0.994444,0.0,NaN,NaN,NaN,0.988889,0.067416,0.000000,0.994444,0.067039,0.000000
48,multiarith,ft_cot,ada,128,16,0.072222,0.994444,0.0,NaN,NaN,NaN,0.938889,0.071006,0.090909,0.944444,0.070588,0.100000
49,multiarith,ft_cot,ada,128,32,0.061111,0.988889,0.0,NaN,NaN,NaN,0.922222,0.066265,0.000000,0.933333,0.065476,0.000000
26,multiarith,ft_cot,ada,,1,0.055556,1.000000,0.0,NaN,NaN,NaN,0.000000,NaN,0.055556,0.961111,0.057803,0.000000
30,multiarith,ft_cot,ada,,2,0.072222,1.000000,0.0,NaN,NaN,NaN,0.994444,0.072626,0.000000,0.994444,0.072626,0.000000
31,multiarith,ft_cot,ada,,4,0.077778,0.994444,0.0,NaN,NaN,NaN,0.961111,0.080925,0.000000,0.961111,0.080925,0.000000
32,multiarith,ft_cot,ada,,8,0.077778,1.000000,0.0,NaN,NaN,NaN,0.983333,0.079096,0.000000,0.983333,0.079096,0.000000
33,multiarith,ft_cot,ada,,16,0.166667,1.000000,0.0,NaN,NaN,NaN,0.983333,0.169492,0.000000,0.983333,0.169492,0.000000
34,multiarith,ft_cot,ada,,32,0.211111,0.977778,0.0,NaN,NaN,NaN,0.938889,0.224852,0.000000,0.961111,0.219653,0.000000
118,multiarith,ft_cot,babbage,8,1,0.033333,0.777778,0.0,NaN,NaN,NaN,0.288889,0.038462,0.031250,0.466667,0.011905,0.052083
126,multiarith,ft_cot,babbage,8,2,0.050000,1.000000,0.0,NaN,NaN,NaN,0.711111,0.054688,0.038462,0.788889,0.049296,0.052632
127,multiarith,ft_cot,babbage,8,4,0.005556,1.000000,0.0,NaN,NaN,NaN,0.938889,0.000000,0.090909,0.927778,0.000000,0.076923
128,multiarith,ft_cot,babbage,8,8,0.022222,0.994444,0.0,NaN,NaN,NaN,0.950000,0.023392,0.000000,0.955556,0.023256,0.000000
129,multiarith,ft_cot,babbage,8,16,0.038889,0.994444,0.0,NaN,NaN,NaN,0.888889,0.037500,0.050000,0.888889,0.037500,0.050000
130,multiarith,ft_cot,babbage,8,32,0.016667,0.977778,0.0,NaN,NaN,NaN,0.933333,0.011905,0.083333,0.955556,0.011628,0.125000
119,multiarith,ft_cot,babbage,32,1,0.050000,1.000000,0.0,NaN,NaN,NaN,0.827778,0.040268,0.096774,0.827778,0.040268,0.096774
131,multiarith,ft_cot,babbage,32,2,0.027778,1.000000,0.0,NaN,NaN,NaN,0.933333,0.029762,0.000000,0.905556,0.030675,0.000000
132,multiarith,ft_cot,babbage,32,4,0.055556,1.000000,0.0,NaN,NaN,NaN,0.955556,0.058140,0.000000,0.950000,0.058480,0.000000
133,multiarith,ft_cot,babbage,32,8,0.044444,1.000000,0.0,NaN,NaN,NaN,0.961111,0.046243,0.000000,0.961111,0.046243,0.000000
134,multiarith,ft_cot,babbage,32,16,0.088889,1.000000,0.0,NaN,NaN,NaN,0.972222,0.085714,0.200000,0.983333,0.084746,0.333333
135,multiarith,ft_cot,babbage,32,32,0.077778,1.000000,0.0,NaN,NaN,NaN,0.933333,0.083333,0.000000,0.933333,0.083333,0.000000
120,multiarith,ft_cot,babbage,128,1,0.094444,0.983333,0.0,NaN,NaN,NaN,0.983333,0.096045,0.000000,0.977778,0.096591,0.000000
136,multiarith,ft_cot,babbage,128,2,0.077778,1.000000,0.0,NaN,NaN,NaN,0.977778,0.079545,0.000000,0.977778,0.079545,0.000000
137,multiarith,ft_cot,babbage,128,4,0.083333,1.000000,0.0,NaN,NaN,NaN,0.972222,0.085714,0.000000,0.977778,0.085227,0.000000
138,multiarith,ft_cot,babbage,128,8,0.094444,1.000000,0.0,NaN,NaN,NaN,0.977778,0.096591,0.000000,0.977778,0.096591,0.000000
139,multiarith,ft_cot,babbage,128,16,0.105556,1.000000,0.0,NaN,NaN,NaN,0.983333,0.107345,0.000000,0.983333,0.107345,0.000000
140,multiarith,ft_cot,babbage,128,32,0.144444,0.994444,0.0,NaN,NaN,NaN,0.972222,0.142857,0.200000,0.983333,0.141243,0.333333
117,multiarith,ft_cot,babbage,,1,0.138889,1.000000,0.0,NaN,NaN,NaN,0.000000,NaN,0.138889,0.994444,0.139665,0.000000
121,multiarith,ft_cot,babbage,,2,0.155556,1.000000,0.0,NaN,NaN,NaN,0.994444,0.156425,0.000000,0.994444,0.156425,0.000000
122,multiarith,ft_cot,babbage,,4,0.133333,1.000000,0.0,NaN,NaN,NaN,0.988889,0.134831,0.000000,0.988889,0.134831,0.000000
123,multiarith,ft_cot,babbage,,8,0.194444,0.994444,0.0,NaN,NaN,NaN,0.977778,0.187500,0.500000,0.983333,0.186441,0.666667
124,multiarith,ft_cot,babbage,,16,0.211111,0.988889,0.0,NaN,NaN,NaN,0.955556,0.220930,0.000000,0.966667,0.218391,0.000000
125,multiarith,ft_cot,babbage,,32,0.300000,1.000000,0.0,NaN,NaN,NaN,0.972222,0.308571,0.000000,0.977778,0.306818,0.000000
210,multiarith,ft_cot,curie,8,1,0.005556,0.616667,0.0,NaN,NaN,NaN,0.388889,0.000000,0.009091,0.544444,0.000000,0.012195
218,multiarith,ft_cot,curie,8,2,0.022222,0.988889,0.0,NaN,NaN,NaN,0.794444,0.020979,0.027027,0.972222,0.022857,0.000000
219,multiarith,ft_cot,curie,8,4,0.027778,1.000000,0.0,NaN,NaN,NaN,1.000000,0.027778,NaN,0.988889,0.028090,0.000000
220,multiarith,ft_cot,curie,8,8,0.072222,1.000000,0.0,NaN,NaN,NaN,0.938889,0.076923,0.000000,0.916667,0.078788,0.000000
221,multiarith,ft_cot,curie,8,16,0.061111,1.000000,0.0,NaN,NaN,NaN,0.944444,0.064706,0.000000,0.944444,0.064706,0.000000
222,multiarith,ft_cot,curie,8,32,0.061111,1.000000,0.0,NaN,NaN,NaN,0.950000,0.064327,0.000000,0.944444,0.064706,0.000000
211,multiarith,ft_cot,curie,32,1,0.122222,1.000000,0.0,NaN,NaN,NaN,0.938889,0.130178,0.000000,0.966667,0.126437,0.000000
223,multiarith,ft_cot,curie,32,2,0.100000,1.000000,0.0,NaN,NaN,NaN,0.966667,0.103448,0.000000,0.955556,0.104651,0.000000
224,multiarith,ft_cot,curie,32,4,0.088889,1.000000,0.0,NaN,NaN,NaN,0.988889,0.089888,0.000000,0.972222,0.091429,0.000000
225,multiarith,ft_cot,curie,32,8,0.127778,1.000000,0.0,NaN,NaN,NaN,0.983333,0.129944,0.000000,0.983333,0.129944,0.000000
226,multiarith,ft_cot,curie,32,16,0.172222,1.000000,0.0,NaN,NaN,NaN,0.977778,0.176136,0.000000,0.977778,0.176136,0.000000
227,multiarith,ft_cot,curie,32,32,0.155556,1.000000,0.0,NaN,NaN,NaN,0.977778,0.153409,0.250000,0.977778,0.153409,0.250000
212,multiarith,ft_cot,curie,128,1,0.177778,0.994444,0.0,NaN,NaN,NaN,0.961111,0.184971,0.000000,0.961111,0.184971,0.000000
228,multiarith,ft_cot,curie,128,2,0.133333,1.000000,0.0,NaN,NaN,NaN,0.944444,0.135294,0.100000,0.938889,0.136095,0.090909
229,multiarith,ft_cot,curie,128,4,0.233333,1.000000,0.0,NaN,NaN,NaN,0.950000,0.233918,0.222222,0.950000,0.233918,0.222222
230,multiarith,ft_cot,curie,128,8,0.277778,1.000000,0.0,NaN,NaN,NaN,0.983333,0.276836,0.333333,0.983333,0.276836,0.333333
231,multiarith,ft_cot,curie,128,16,0.344444,1.000000,0.0,NaN,NaN,NaN,0.961111,0.358382,0.000000,0.966667,0.356322,0.000000
232,multiarith,ft_cot,curie,128,32,0.305556,1.000000,0.0,NaN,NaN,NaN,0.961111,0.312139,0.142857,0.961111,0.312139,0.142857
209,multiarith,ft_cot,curie,,1,0.344444,1.000000,0.0,NaN,NaN,NaN,0.000000,NaN,0.344444,0.994444,0.346369,0.000000
213,multiarith,ft_cot,curie,,2,0.272222,1.000000,0.0,NaN,NaN,NaN,0.977778,0.278409,0.000000,0.977778,0.278409,0.000000
214,multiarith,ft_cot,curie,,4,0.338889,1.000000,0.0,NaN,NaN,NaN,0.950000,0.356725,0.000000,0.950000,0.356725,0.000000
215,multiarith,ft_cot,curie,,8,0.472222,1.000000,0.0,NaN,NaN,NaN,0.983333,0.480226,0.000000,0.988889,0.477528,0.000000
216,multiarith,ft_cot,curie,,16,0.416667,1.000000,0.0,NaN,NaN,NaN,0.983333,0.423729,0.000000,0.983333,0.423729,0.000000
217,multiarith,ft_cot,curie,,32,0.555556,1.000000,0.0,NaN,NaN,NaN,0.988889,0.556180,0.500000,0.988889,0.556180,0.500000
25,multiarith,zs_cot,ada,,,0.038889,0.861111,0.0,0.000,NaN,0.038889,NaN,NaN,NaN,NaN,NaN,NaN
116,multiarith,zs_cot,babbage,,,0.033333,0.927778,0.0,0.000,NaN,0.033333,NaN,NaN,NaN,NaN,NaN,NaN
208,multiarith,zs_cot,curie,,,0.050000,0.944444,0.0,0.000,NaN,0.050000,NaN,NaN,NaN,NaN,NaN,NaN
2,multiarith,zs_cot,idavinci,,,0.773333,0.978333,0.0,0.945,0.798942,0.333333,NaN,NaN,NaN,NaN,NaN,NaN

In [145]:
summary.to_csv("evaluation_summary.csv")

In [146]:
selection = fs.dataset == "multiarith"
selection = selection & (fs.method == "ft_cot")
selection = selection & (fs.shot == 128)
selection = selection & (fs.aug == 16)
selection = selection & (fs.base_model== "curie")

In [147]:
accuracy_summary = defaultdict(list)

fs = summary
s = summary.loc[:,["dataset", "method", "shot", "aug"]].drop_duplicates()
for d, m, s, a in zip(s.dataset, s.method, s.shot, s.aug):
    accuracy_summary["dataset"].append(d)
    accuracy_summary["method"].append(m)
    accuracy_summary["shot"].append(s)
    accuracy_summary["aug"].append(a)
    for model in ["ada", "babbage", "curie", "idavinci"]:
        sums = []
        selection = fs.dataset == d 
        selection = selection & (fs.method == m)
        selection = selection & (fs.shot == s)
        selection = selection & (fs.aug == a)
        selection = selection & (fs.base_model == model)
    
        try:
            accuracy = fs[selection].accuracy.item()
        except ValueError:
            accuracy = None
        accuracy_summary[model].append(accuracy)
        
accuracy_summary = pd.DataFrame(accuracy_summary)
accuracy_summary

,dataset,method,shot,aug,ada,babbage,curie,idavinci
0,addsub,ft,,,0.084034,0.176471,0.252101,NaN
1,addsub,ft_cot,8,1,0.008403,0.033613,0.126050,NaN
2,addsub,ft_cot,32,1,0.050420,0.042017,0.184874,NaN
3,addsub,ft_cot,128,1,0.025210,0.092437,0.226891,NaN
4,addsub,ft_cot,,1,0.067227,0.117647,0.201681,NaN
5,addsub,zs_cot,,,0.000000,0.000000,0.025210,0.757246
6,aqua,ft,,,0.244094,0.212598,0.153543,NaN
7,aqua,ft_cot,32,1,0.141732,0.208661,0.090551,NaN
8,aqua,ft_cot,128,1,0.177165,0.149606,0.125984,NaN
9,aqua,ft_cot,,1,0.165354,0.153543,0.161417,NaN
10,aqua,ft_cot,8,1,NaN,0.141732,0.118110,NaN
11,aqua,zs_cot,,,0.251969,0.216535,0.212598,0.296300
12,coin_flip,ft,,,1.000000,1.000000,0.720000,NaN
13,coin_flip,ft_cot,8,1,0.446667,0.446667,0.453333,NaN
14,coin_flip,ft_cot,32,1,0.633333,0.633333,1.000000,NaN
15,coin_flip,ft_cot,128,1,0.973333,0.993333,0.986667,NaN
16,coin_flip,ft_cot,,1,0.993333,1.000000,0.980000,NaN
17,coin_flip,zs_cot,,,0.046667,0.473333,0.466667,0.886000
18,commonsense_qa,ft,,,0.516790,0.709255,0.761671,NaN
19,commonsense_qa,ft_cot,8,1,0.152334,0.127764,0.138411,NaN
20,commonsense_qa,ft_cot,32,1,0.158886,0.187551,0.194922,NaN
21,commonsense_qa,ft_cot,128,1,0.200655,0.234234,0.226044,NaN
22,commonsense_qa,ft_cot,,1,0.303030,0.406224,0.510238,NaN
23,commonsense_qa,zs_cot,,,0.195741,0.202293,0.199836,0.598604
24,date_understanding,ft,,,0.234234,0.315315,0.144144,NaN
25,date_understanding,ft_cot,8,1,0.207207,0.162162,0.009009,NaN
26,date_understanding,ft_cot,32,1,0.153153,0.189189,0.180180,NaN
27,date_understanding,ft_cot,128,1,0.135135,0.234234,0.261261,NaN
28,date_understanding,ft_cot,,1,0.171171,0.387387,0.603604,NaN
29,date_understanding,zs_cot,,,0.108108,0.144144,0.153153,0.682927
30,gsm8k,ft,,,0.050796,0.053829,0.061410,NaN
31,gsm8k,ft_cot,8,1,0.012130,0.016679,0.009098,NaN
32,gsm8k,ft_cot,32,1,0.018954,0.018196,0.024261,NaN
33,gsm8k,ft_cot,128,1,0.016679,0.016679,0.026535,NaN
34,gsm8k,ft_cot,,1,0.028810,0.038666,0.072024,NaN
35,gsm8k,zs_cot,,,0.015163,0.016679,0.023503,0.420723
36,last_letter_concatenation,ft,,,0.286667,0.300000,0.326667,NaN
37,last_letter_concatenation,ft_cot,8,1,0.000000,0.000000,0.020000,NaN
38,last_letter_concatenation,ft_cot,32,1,0.060000,0.133333,0.213333,NaN
39,last_letter_concatenation,ft_cot,128,1,0.366667,0.400000,0.426667,NaN
40,last_letter_concatenation,ft_cot,,1,0.506667,0.506667,0.520000,NaN
41,last_letter_concatenation,zs_cot,,,0.000000,0.000000,0.000000,0.570000
42,multiarith,ft,,,0.088889,0.177778,0.150000,NaN
43,multiarith,ft_cot,8,1,0.044444,0.033333,0.005556,NaN
44,multiarith,ft_cot,8,2,0.033333,0.050000,0.022222,NaN
45,multiarith,ft_cot,8,4,0.016667,0.005556,0.027778,NaN
46,multiarith,ft_cot,8,8,0.033333,0.022222,0.072222,NaN
47,multiarith,ft_cot,8,16,0.022222,0.038889,0.061111,NaN
48,multiarith,ft_cot,8,32,0.027778,0.016667,0.061111,NaN
49,multiarith,ft_cot,32,1,0.038889,0.050000,0.122222,NaN
50,multiarith,ft_cot,32,2,0.038889,0.027778,0.100000,NaN
51,multiarith,ft_cot,32,4,0.027778,0.055556,0.088889,NaN
52,multiarith,ft_cot,32,8,0.027778,0.044444,0.127778,NaN
53,multiarith,ft_cot,32,16,0.033333,0.088889,0.172222,NaN
54,multiarith,ft_cot,32,32,0.011111,0.077778,0.155556,NaN
55,multiarith,ft_cot,128,1,0.061111,0.094444,0.177778,NaN
56,multiarith,ft_cot,128,2,0.033333,0.077778,0.133333,NaN
57,multiarith,ft_cot,128,4,0.072222,0.083333,0.233333,NaN
58,multiarith,ft_cot,128,8,0.066667,0.094444,0.277778,NaN
59,multiarith,ft_cot,128,16,0.072222,0.105556,0.344444,NaN
60,multiarith,ft_cot,128,32,0.061111,0.144444,0.305556,NaN
61,multiarith,ft_cot,,1,0.055556,0.138889,0.344444,NaN
62,multiarith,ft_cot,,2,0.072222,0.155556,0.272222,NaN
63,multiarith,ft_cot,,4,0.077778,0.133333,0.338889,NaN
64,multiarith,ft_cot,,8,0.077778,0.194444,0.472222,NaN
65,multiarith,ft_cot,,16,0.166667,0.211111,0.416667,NaN
66,multiarith,ft_cot,,32,0.211111,0.300000,0.555556,NaN
67,multiarith,zs_cot,,,0.038889,0.033333,0.050000,0.773333
68,single_eq,ft,,,0.098684,0.118421,0.243421,NaN
69,single_eq,ft_cot,8,1,0.006579,0.006579,0.052632,NaN
70,single_eq,ft_cot,32,1,0.006579,0.026316,0.085526,NaN
71,single_eq,ft_cot,128,1,0.046053,0.072368,0.138158,NaN
72,single_eq,ft_cot,,1,0.065789,0.111842,0.210526,NaN
73,single_eq,zs_cot,,,0.006579,0.000000,0.013158,0.811798
74,strategy_qa,ft,,,0.604076,0.606987,0.652111,NaN
75,strategy_qa,ft_cot,8,1,0.189229,0.327511,0.327511,NaN
76,strategy_qa,ft_cot,32,1,0.360990,0.393013,0.403202,NaN
77,strategy_qa,ft_cot,128,1,0.381368,0.394469,0.436681,NaN
78,strategy_qa,ft_cot,,1,0.467249,0.465793,0.471616,NaN
79,strategy_qa,zs_cot,,,0.177584,0.379913,0.510917,0.533999
80,svamp,ft,,,0.076667,0.143333,0.206667,NaN
81,svamp,ft_cot,8,1,0.020000,0.010000,0.020000,NaN
82,svamp,ft_cot,32,1,0.033333,0.040000,0.080000,NaN
83,svamp,ft_cot,128,1,0.036667,0.030000,0.073333,NaN
84,svamp,ft_cot,,1,0.043333,0.073333,0.123333,NaN
85,svamp,zs_cot,,,0.030000,0.010000,0.013333,0.640000
86,tracking_shuffled_objects,ft,,,0.324444,0.302222,0.337778,NaN
87,tracking_shuffled_objects,ft_cot,8,1,0.346667,0.271111,0.284444,NaN
88,tracking_shuffled_objects,ft_cot,32,1,0.297778,0.320000,0.342222,NaN
89,tracking_shuffled_objects,ft_cot,128,1,0.328889,0.364444,0.475556,NaN
90,tracking_shuffled_objects,ft_cot,,1,0.488889,0.537778,0.640000,NaN
91,tracking_shuffled_objects,zs_cot,,,0.346667,0.382222,0.311111,0.529333

In [148]:
accuracy_summary.to_csv("evaluation_summary_accuracy.csv")

In [149]:
pd.DataFrame(accuracy_summary).to_csv("evaluation_summary_accuracy.csv")

### Common Verbal Names

In [122]:
DATASET_NAMES = {
    "single_eq": "SingleEq",
    "addsub": "AddSub",
    "multiarith": "MultiArith",
    "gsm8k": "GSM8K",
    "aqua": "AQUA",
    "svamp": "SVAMP",
    "commonsense_qa": "Common",  # SenseQA
    "strategy_qa": "Strategy",  # QA
    "date_understanding": "Date",  # Understanding
    "tracking_shuffled_objects": "Shuffled",  # Objects
    "last_letter_concatenation": "Last Letter",  # (4 words)
    "coin_flip": "Coin Flip",  # (4 times)

}

In [123]:
FULL_DATASET_NAMES = {
    "single_eq": "SingleEq",
    "addsub": "AddSub",
    "multiarith": "MultiArith",
    "gsm8k": "GSM8K",
    "aqua": "AQUA",
    "svamp": "SVAMP",
    "commonsense_qa": "CommonSenseQA",  # SenseQA
    "strategy_qa": "StrategyQA",  # QA
    "date_understanding": "Date Understanding",  # Understanding
    "tracking_shuffled_objects": "Shuffled Objects",  # Objects
    "last_letter_concatenation": "Last Letter (4 words)",  # (4 words)
    "coin_flip": "Coin Flip (4 words)",  # (4 times)

}

In [124]:
METHOD_NAMES = {
    "zs": "Zero-shot",
    "ft": "Fine-tune",
    "zs_cot": "Zero-shot-CoT",
    "ft_cot": "Fine-tune-CoT",
    "ft_cot_008shot": "8-shot Ft-CoT",
    "ft_cot_032shot": "32-shot Ft-CoT",
    "ft_cot_128shot": "128-shot Ft-CoT",
}

In [125]:
DATASETS = ["single_eq", "addsub", "multiarith", "gsm8k", "aqua", "svamp", "commonsense_qa",
            "strategy_qa", "date_understanding", "tracking_shuffled_objects",
            "last_letter_concatenation", "coin_flip"]

### Table 1.

In [126]:
lines = [
    ["single_eq", "addsub", "multiarith", "gsm8k", "aqua", "svamp"],
    ["commonsense_qa", "strategy_qa", "date_understanding", "tracking_shuffled_objects", "last_letter_concatenation", "coin_flip"],
]

In [127]:
table1_dfs = []

base_model = "curie"
for line in lines:
    data = defaultdict(dict)
    for dataset in line:
        for method in ["ft", "zs_cot", "ft_cot"]:
            try:
                s = summary
                s = s[s.dataset == dataset]
                s = s[s.method == method]
                s = s[s.base_model == base_model]
                s = s[s.shot == ""]
                s = s[s.aug.isin([1, ""])]
                accuracy = s.accuracy.item() * 100
                accuracy = "{:.2f}".format(accuracy)
            except (KeyError, ValueError):
                accuracy = ""
            
            dataset_name = DATASET_NAMES[dataset]
            method_name = METHOD_NAMES[method]
            data[dataset_name][method_name] = accuracy
    table1_dfs.append(pd.DataFrame(data))

In [128]:
table1_dfs[0]

              SingleEq AddSub MultiArith GSM8K   AQUA  SVAMP
Fine-tune        24.34  25.21      15.00  6.14  15.35  20.67
Zero-shot-CoT     1.32   2.52       5.00  2.35  21.26   1.33
Fine-tune-CoT    21.05  20.17      34.44  7.20  16.14  12.33

In [129]:
table1_dfs[1]

              Common Strategy   Date Shuffled Last Letter Coin Flip
Fine-tune      76.17    65.21  14.41    33.78       32.67     72.00
Zero-shot-CoT  19.98    51.09  15.32    31.11        0.00     46.67
Fine-tune-CoT  51.02    47.16  60.36    64.00       52.00     98.00

In [130]:
print(table1_dfs[0].to_latex())

\begin{tabular}{lllllll}
\toprule
{} & SingleEq & AddSub & MultiArith & GSM8K &   AQUA &  SVAMP \\
\midrule
Fine-tune     &    24.34 &  25.21 &      15.00 &  6.14 &  15.35 &  20.67 \\
Zero-shot-CoT &     1.32 &   2.52 &       5.00 &  2.35 &  21.26 &   1.33 \\
Fine-tune-CoT &    21.05 &  20.17 &      34.44 &  7.20 &  16.14 &  12.33 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_31500/2509386988.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(table1_dfs[0].to_latex())

In [131]:
print(table1_dfs[1].to_latex())

\begin{tabular}{lllllll}
\toprule
{} & Common & Strategy &   Date & Shuffled & Last Letter & Coin Flip \\
\midrule
Fine-tune     &  76.17 &    65.21 &  14.41 &    33.78 &       32.67 &     72.00 \\
Zero-shot-CoT &  19.98 &    51.09 &  15.32 &    31.11 &        0.00 &     46.67 \\
Fine-tune-CoT &  51.02 &    47.16 &  60.36 &    64.00 &       52.00 &     98.00 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_31500/2363446589.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(table1_dfs[1].to_latex())

### Table 2.

In [132]:
MODEL_NAMES = {
    "davinci": "175B",
    "curie": "6.7B",
    "babbage": "1.3B",
    "ada": "0.3B",
    "idavinci": "i175B",
    "icurie": "i6.7B",
    "ibabbage": "i1.3B",
    "iada": "i0.3B",
}

In [133]:
datasets = [
#     "multiarith", "gsm8k", "date_understanding", "tracking_shuffled_objects", "last_letter_concatenation", "coin_flip",
    "single_eq", "addsub", "multiarith", "gsm8k", "aqua", "svamp", "commonsense_qa", "strategy_qa", "date_understanding", "tracking_shuffled_objects", "last_letter_concatenation", "coin_flip",
]
#     "single_eq", "addsub", "multiarith", "gsm8k", "aqua", "svamp", "commonsense_qa", "strategy_qa", "date_understanding", "tracking_shuffled_objects", "last_letter_concatenation", "coin_flip",

In [134]:
data = defaultdict(dict)

for dataset in datasets:
    for method in ["zs_cot", "ft", "ft_cot"]:
        if method == "zs_cot":
            base_models = ["idavinci", "ada", "babbage", "curie"]
        else:
            base_models = ["ada", "babbage", "curie"]

        for base_model in base_models:
            try:
                s = summary
                s = s[s.dataset == dataset]
                s = s[s.method == method]
                s = s[s.base_model == base_model]
                s = s[s.shot == ""]
                s = s[s.aug.isin([1, ""])]
                accuracy = s.accuracy.item() * 100
                accuracy = "{:.2f}".format(accuracy)
            except (KeyError, ValueError):
                accuracy = ""

            dataset_name = DATASET_NAMES[dataset]
            method_name = METHOD_NAMES[method]
            model_name = MODEL_NAMES[base_model]
            data[dataset_name][(method_name, model_name)] = accuracy
            
table2_df = pd.DataFrame(data)

In [135]:
table2_df

                    SingleEq AddSub MultiArith  GSM8K   AQUA  SVAMP Common  \
Zero-shot-CoT i175B    81.18  75.72      77.33  42.07  29.63  64.00  59.86
              0.3B      0.66   0.00       3.89   1.52  25.20   3.00  19.57
              1.3B      0.00   0.00       3.33   1.67  21.65   1.00  20.23
              6.7B      1.32   2.52       5.00   2.35  21.26   1.33  19.98
Fine-tune     0.3B      9.87   8.40       8.89   5.08  24.41   7.67  51.68
              1.3B     11.84  17.65      17.78   5.38  21.26  14.33  70.93
              6.7B     24.34  25.21      15.00   6.14  15.35  20.67  76.17
Fine-tune-CoT 0.3B      6.58   6.72       5.56   2.88  16.54   4.33  30.30
              1.3B     11.18  11.76      13.89   3.87  15.35   7.33  40.62
              6.7B     21.05  20.17      34.44   7.20  16.14  12.33  51.02

                    Strategy   Date Shuffled Last Letter Coin Flip
Zero-shot-CoT i175B    53.40  68.29    52.93       57.00     88.60
              0.3B     17.76  10.81    34.67        0.00      4.67
              1.3B     37.99  14.41    38.22        0.00     47.33
              6.7B     51.09  15.32    31.11        0.00     46.67
Fine-tune     0.3B     60.41  23.42    32.44       28.67    100.00
              1.3B     60.70  31.53    30.22       30.00    100.00
              6.7B     65.21  14.41    33.78       32.67     72.00
Fine-tune-CoT 0.3B     46.72  17.12    48.89       50.67     99.33
              1.3B     46.58  38.74    53.78       50.67    100.00
              6.7B     47.16  60.36    64.00       52.00     98.00

In [90]:
print(table2_df.to_latex())

\begin{tabular}{llllllllllllll}
\toprule
              &      & SingleEq & AddSub & MultiArith &  GSM8K &   AQUA &  SVAMP & Common & Strategy &   Date & Shuffled & Last Letter & Coin Flip \\
\midrule
Zero-shot-CoT & i175B &    81.18 &  75.72 &      77.33 &  42.07 &  29.63 &  64.00 &  59.86 &    53.40 &  68.29 &    52.93 &       57.00 &     88.60 \\
              & 0.3B &     0.66 &   0.00 &       3.89 &   1.52 &  25.20 &   3.00 &  19.57 &    17.76 &  10.81 &    34.67 &        0.00 &      4.67 \\
              & 1.3B &     0.00 &   0.00 &       3.33 &   1.67 &  21.65 &   1.00 &  20.23 &    37.99 &  14.41 &    38.22 &        0.00 &     47.33 \\
              & 6.7B &     1.32 &   2.52 &       5.00 &   2.35 &  21.26 &   1.33 &  19.98 &    51.09 &  15.32 &    31.11 &        0.00 &     46.67 \\
Fine-tune & 0.3B &     9.87 &   8.40 &       8.89 &   5.08 &  24.41 &   7.67 &  51.68 &    60.41 &  23.42 &    32.44 &       28.67 &    100.00 \\
              & 1.3B &    11.84 &  17.65 &      17.78 &   5.38 &  21.26 &  14.33 &  70.93 &    60.70 &  31.53 &    30.22 &       30.00 &    100.00 \\
              & 6.7B &    24.34 &  25.21 &      15.00 &   6.14 &  15.35 &  20.67 &  76.17 &    65.21 &  14.41 &    33.78 &       32.67 &     72.00 \\
Fine-tune-CoT & 0.3B &     6.58 &   6.72 &       5.56 &   2.88 &  16.54 &   4.33 &  30.30 &    46.72 &  17.12 &    48.89 &       50.67 &     99.33 \\
              & 1.3B &    11.18 &  11.76 &      13.89 &   3.87 &  15.35 &   7.33 &  40.62 &    46.58 &  38.74 &    53.78 &       50.67 &    100.00 \\
              & 6.7B &    21.05 &  20.17 &      34.44 &   7.20 &  16.14 &  12.33 &  51.02 &    47.16 &  60.36 &    64.00 &       52.00 &     98.00 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_31500/366782163.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(table2_df.to_latex())

### Table 3.

In [136]:
lines = [
    ["single_eq", "addsub", "multiarith", "gsm8k", "aqua", "svamp"],
    ["commonsense_qa", "strategy_qa", "date_understanding", "tracking_shuffled_objects", "last_letter_concatenation", "coin_flip"],
]

In [138]:
data = defaultdict(dict)

datasets = ALL_DATASETS
base_model = "curie"
for dataset in datasets:
    dataset_name = FULL_DATASET_NAMES[dataset]
    shots = ["", 8, 32, 128, ""]
    methods = ["zs_cot"] + ["ft_cot"] * 4

    for method, shot in zip(methods, shots):
        method_name = METHOD_NAMES[method]
        if shot:
            shot_name = "{}-shot".format(shot)
        else:
            shot_name = ""
        try:
            s = summary
            s = s[s.dataset == dataset]
            s = s[s.method == method]
            s = s[s.base_model == base_model]
            s = s[s.aug.isin(["", 1])]
            s = s[s.shot == shot]
            accuracy = s.accuracy.item() * 100
            accuracy = "{:.2f}".format(accuracy)
        except (KeyError, ValueError):
            accuracy = ""
        data[dataset_name][(method_name, shot_name)] = accuracy

table3 = pd.DataFrame(data).T
table3

                      Zero-shot-CoT Fine-tune-CoT
                                           8-shot 32-shot 128-shot
SingleEq                       1.32          5.26    8.55    13.82  21.05
AddSub                         2.52         12.61   18.49    22.69  20.17
MultiArith                     5.00          0.56   12.22    17.78  34.44
GSM8K                          2.35          0.91    2.43     2.65   7.20
AQUA                          21.26         11.81    9.06    12.60  16.14
SVAMP                          1.33          2.00    8.00     7.33  12.33
Date Understanding            15.32          0.90   18.02    26.13  60.36
Coin Flip (4 words)           46.67         45.33  100.00    98.67  98.00
Shuffled Objects              31.11         28.44   34.22    47.56  64.00
Last Letter (4 words)          0.00          2.00   21.33    42.67  52.00
CommonSenseQA                 19.98         13.84   19.49    22.60  51.02
StrategyQA                    51.09         32.75   40.32    43.67  47.16

In [140]:
print(table3.to_latex())

\begin{tabular}{llllll}
\toprule
{} & Zero-shot-CoT & \multicolumn{4}{l}{Fine-tune-CoT} \\
{} &        8-shot & 32-shot & \multicolumn{2}{l}{128-shot} \\
\midrule
SingleEq              &          1.32 &          5.26 &    8.55 &    13.82 &  21.05 \\
AddSub                &          2.52 &         12.61 &   18.49 &    22.69 &  20.17 \\
MultiArith            &          5.00 &          0.56 &   12.22 &    17.78 &  34.44 \\
GSM8K                 &          2.35 &          0.91 &    2.43 &     2.65 &   7.20 \\
AQUA                  &         21.26 &         11.81 &    9.06 &    12.60 &  16.14 \\
SVAMP                 &          1.33 &          2.00 &    8.00 &     7.33 &  12.33 \\
Date Understanding    &         15.32 &          0.90 &   18.02 &    26.13 &  60.36 \\
Coin Flip (4 words)   &         46.67 &         45.33 &  100.00 &    98.67 &  98.00 \\
Shuffled Objects      &         31.11 &         28.44 &   34.22 &    47.56 &  64.00 \\
Last Letter (4 words) &          0.00 &          2.00 &   21.33 &    42.67 &  52.00 \\
CommonSenseQA         &         19.98 &         13.84 &   19.49 &    22.60 &  51.02 \\
StrategyQA            &         51.09 &         32.75 &   40.32 &    43.67 &  47.16 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_31500/576120982.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(table3.to_latex())

### Table 4.

In [150]:
data = defaultdict(list)

dataset = "multiarith"
dataset_name = FULL_DATASET_NAMES[dataset]
ft_augs = [1, 2, 4, 8, 16, 32]
methods = ["zs_cot"] + ["ft_cot"] * len(ft_augs)
augs = [""] + ft_augs
for method, aug in zip(methods, augs):
    data[("Method", "")].append(METHOD_NAMES[method])
    data[("Reasoning", "Samples")].append(aug)
    for base_model in ["ada", "babbage", "curie"]:
        try:
            s = summary
            s = s[s.dataset == dataset]
            s = s[s.method == method]
            s = s[s.base_model == base_model]
            s = s[s.aug == aug]
            s = s[s.shot == ""]
            accuracy = s.accuracy.item() * 100
            accuracy = "{:.2f}".format(accuracy)
        except (KeyError, ValueError):
            accuracy = ""

        base_model_name = MODEL_NAMES[base_model]
        
        data[("Model", base_model_name)].append(accuracy)
        
table4 = pd.DataFrame(data)
table4

          Method Reasoning  Model
                   Samples   0.3B   1.3B   6.7B
0  Zero-shot-CoT             3.89   3.33   5.00
1  Fine-tune-CoT         1   5.56  13.89  34.44
2  Fine-tune-CoT         2   7.22  15.56  27.22
3  Fine-tune-CoT         4   7.78  13.33  33.89
4  Fine-tune-CoT         8   7.78  19.44  47.22
5  Fine-tune-CoT        16  16.67  21.11  41.67
6  Fine-tune-CoT        32  21.11  30.00  55.56

In [151]:
print(table4.style.hide(axis="index").to_latex(multicol_align="c", hrules=True))

\begin{tabular}{lllll}
\toprule
Method & Reasoning & \multicolumn{3}{c}{Model} \\
 & Samples & 0.3B & 1.3B & 6.7B \\
\midrule
Zero-shot-CoT &  & 3.89 & 3.33 & 5.00 \\
Fine-tune-CoT & 1 & 5.56 & 13.89 & 34.44 \\
Fine-tune-CoT & 2 & 7.22 & 15.56 & 27.22 \\
Fine-tune-CoT & 4 & 7.78 & 13.33 & 33.89 \\
Fine-tune-CoT & 8 & 7.78 & 19.44 & 47.22 \\
Fine-tune-CoT & 16 & 16.67 & 21.11 & 41.67 \\
Fine-tune-CoT & 32 & 21.11 & 30.00 & 55.56 \\
\bottomrule
\end{tabular}

### Table 5.

In [379]:
data = defaultdict(list)

dataset = "multiarith"
dataset_name = FULL_DATASET_NAMES[dataset]
ft_shots = [8, 32, 128]
ft_augs = [1, 2, 4, 8, 16, 32]
n_shots, n_augs = len(ft_shots), len(ft_augs)
methods = ["zs_cot"] + ["ft_cot"] + ["ft_cot"] * n_shots * n_augs
shots = ["", ""] + np.repeat(ft_shots, n_augs).tolist()
augs = ["", 1] + ft_augs * n_shots

for method, shot, aug in zip(methods, shots, augs):
    data[("Method", "")].append(METHOD_NAMES[method])
    data[("Shots", "")].append(shot)
    data[("Reasoning", "Samples")].append(aug)
    for base_model in ["ada", "babbage", "curie"]:
        try:
            s = summary
            s = s[s.dataset == dataset]
            s = s[s.method == method]
            s = s[s.base_model == base_model]
            s = s[s.aug == aug]
            s = s[s.shot == shot]
            accuracy = s.accuracy.item() * 100
            accuracy = "{:.2f}".format(accuracy)
        except (KeyError, ValueError):
            accuracy = ""

        base_model_name = MODEL_NAMES[base_model]
        
        data[("Model", base_model_name)].append(accuracy)
        
table5 = pd.DataFrame(data)
table5

           Method Shots Reasoning Model
                          Samples  0.3B   1.3B   6.7B
0   Zero-shot-CoT                  3.89   3.33   5.00
1   Fine-tune-CoT               1  5.56  13.89  34.44
2   Fine-tune-CoT     8         1  4.44   3.33   0.56
3   Fine-tune-CoT     8         2  3.33   5.00   2.22
4   Fine-tune-CoT     8         4  1.67   0.56   2.78
5   Fine-tune-CoT     8         8  3.33   2.22   7.22
6   Fine-tune-CoT     8        16  2.22   3.89   6.11
7   Fine-tune-CoT     8        32  2.78   1.67   6.11
8   Fine-tune-CoT    32         1  3.89   5.00  12.22
9   Fine-tune-CoT    32         2  3.89   2.78  10.00
10  Fine-tune-CoT    32         4  2.78   5.56   8.89
11  Fine-tune-CoT    32         8  2.78   4.44  12.78
12  Fine-tune-CoT    32        16  3.33   8.89  17.22
13  Fine-tune-CoT    32        32  1.11   7.78  15.56
14  Fine-tune-CoT   128         1  6.11   9.44  17.78
15  Fine-tune-CoT   128         2  3.33   7.78  13.33
16  Fine-tune-CoT   128         4  7.22   8.33  23.33
17  Fine-tune-CoT   128         8  6.67   9.44  27.78
18  Fine-tune-CoT   128        16  7.22  10.56  34.44
19  Fine-tune-CoT   128        32  6.11  14.44  30.56

In [380]:
print(table5.style.hide(axis="index").to_latex(multicol_align="c", hrules=True))

\begin{tabular}{llllll}
\toprule
Method & Shots & Reasoning & \multicolumn{3}{c}{Model} \\
 &  & Samples & 0.3B & 1.3B & 6.7B \\
\midrule
Zero-shot-CoT &  &  & 3.89 & 3.33 & 5.00 \\
Fine-tune-CoT &  & 1 & 5.56 & 13.89 & 34.44 \\
Fine-tune-CoT & 8 & 1 & 4.44 & 3.33 & 0.56 \\
Fine-tune-CoT & 8 & 2 & 3.33 & 5.00 & 2.22 \\
Fine-tune-CoT & 8 & 4 & 1.67 & 0.56 & 2.78 \\
Fine-tune-CoT & 8 & 8 & 3.33 & 2.22 & 7.22 \\
Fine-tune-CoT & 8 & 16 & 2.22 & 3.89 & 6.11 \\
Fine-tune-CoT & 8 & 32 & 2.78 & 1.67 & 6.11 \\
Fine-tune-CoT & 32 & 1 & 3.89 & 5.00 & 12.22 \\
Fine-tune-CoT & 32 & 2 & 3.89 & 2.78 & 10.00 \\
Fine-tune-CoT & 32 & 4 & 2.78 & 5.56 & 8.89 \\
Fine-tune-CoT & 32 & 8 & 2.78 & 4.44 & 12.78 \\
Fine-tune-CoT & 32 & 16 & 3.33 & 8.89 & 17.22 \\
Fine-tune-CoT & 32 & 32 & 1.11 & 7.78 & 15.56 \\
Fine-tune-CoT & 128 & 1 & 6.11 & 9.44 & 17.78 \\
Fine-tune-CoT & 128 & 2 & 3.33 & 7.78 & 13.33 \\
Fine-tune-CoT & 128 & 4 & 7.22 & 8.33 & 23.33 \\
Fine-tune-CoT & 128 & 8 & 6.67 & 9.44 & 27.78 \\
Fine-tune-CoT & 128 & 16 & 7.22 & 10.56 & 34.44 \\
Fine-tune-CoT & 128 & 32 & 6.11 & 14.44 & 30.56 \\
\bottomrule
\end{tabular}

In [119]:
data = defaultdict(dict)

base_model = "babbage"
for dataset in sum(lines, []):
    for method in ["zs_cot", "ft_cot_008shot", "ft_cot_032shot", "ft_cot_128shot", "ft_cot"]:
        try:
            i = summary.dataset == dataset
            i = i & (summary.method == method)
            i = i & (summary.base_model == base_model)
            accuracy = summary.accuracy[i].item() * 100
            accuracy = "{:.2f}".format(accuracy)
        except (KeyError, ValueError):
            accuracy = ""

        dataset_name = FULL_DATASET_NAMES[dataset]
        if "ft_cot" in method:
            method_name = METHOD_NAMES["ft_cot"]
        else:
            method_name = METHOD_NAMES[method]
        
        size = ""
        if method == "ft_cot":
            size = "Full"
        if "008" in method:
            size = "8-shot"
        elif "032" in method: 
            size = "32-shot"
        elif "128" in method: 
            size = "128-shot"
        data[(method_name, size)][dataset_name] = accuracy
table3_babbage = pd.DataFrame(data)

In [120]:
table3_babbage

                      Zero-shot-CoT Fine-tune-CoT
                                           8-shot 32-shot 128-shot    Full
SingleEq
AddSub
MultiArith                     3.33          3.33    5.00     9.44   13.89
GSM8K                          1.67          1.67    1.82     1.67    3.87
AQUA
SVAMP
CommonSenseQA
StrategyQA
Date Understanding            14.41         16.22   18.92    23.42   38.74
Shuffled Objects              38.22         27.11   32.00    36.44   53.78
Last Letter (4 words)          0.00          0.00   13.33    40.00   50.67
Coin Flip (4 words)           47.33         44.67   63.33    99.33  100.00

In [88]:
print(table1_dfs[0].to_latex())

\begin{tabular}{lllllll}
\toprule
{} & SingleEq & AddSub & MultiArith & GSM8K & AQUA & SVAMP \\
\midrule
Fine-tune     &          &        &      15.00 &  6.14 &      &       \\
Zero-shot-CoT &          &        &       5.00 &  2.35 &      &       \\
Fine-tune-CoT &          &        &      34.44 &  7.20 &      &       \\
\bottomrule
\end{tabular}

/tmp/ipykernel_105104/2509386988.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(table1_dfs[0].to_latex())

In [89]:
print(table1_dfs[1].to_latex())

\begin{tabular}{lllllll}
\toprule
{} & Common & Strategy &   Date & Shuffled & Last Letter & Coin Flip \\
\midrule
Fine-tune     &        &          &  14.41 &    33.78 &       32.67 &     72.00 \\
Zero-shot-CoT &        &          &  15.32 &    31.11 &        0.00 &     46.67 \\
Fine-tune-CoT &        &          &  60.36 &    64.00 &       52.00 &     98.00 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_105104/2363446589.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(table1_dfs[1].to_latex())